language: android 

jdk:
  - oraclejdk8 

android:
  components:
    - tools
    - build-tools-24.0.2
    - android-24
    - platform-tools
    - extra-android-support
    - extra-android-m2repository
